//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Single TriggerValue
        {
            get
            {
                return SteamVR_Actions.default_TriggerValue;
            }
        }
        
        public virtual SteamVR_Action_Boolean TriggerTouch
        {
            get
            {
                return SteamVR_Actions.default_TriggerTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean PrimaryButton
        {
            get
            {
                return SteamVR_Actions.default_PrimaryButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean PrimaryTouch
        {
            get
            {
                return SteamVR_Actions.default_PrimaryTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean SecondaryButton
        {
            get
            {
                return SteamVR_Actions.default_SecondaryButton;
            }
        }
        
        public virtual SteamVR_Action_Boolean SecondaryTouch
        {
            get
            {
                return SteamVR_Actions.default_SecondaryTouch;
            }
        }
        
        public virtual SteamVR_Action_Single GripValue
        {
            get
            {
                return SteamVR_Actions.default_GripValue;
            }
        }
        
        public virtual SteamVR_Action_Vector2 JoystickValue
        {
            get
            {
                return SteamVR_Actions.default_JoystickValue;
            }
        }
        
        public virtual SteamVR_Action_Boolean JoystickClick
        {
            get
            {
                return SteamVR_Actions.default_JoystickClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean JoystickTouch
        {
            get
            {
                return SteamVR_Actions.default_JoystickTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean GripTouch
        {
            get
            {
                return SteamVR_Actions.default_GripTouch;
            }
        }
        
        public virtual SteamVR_Action_Boolean TriggerClick
        {
            get
            {
                return SteamVR_Actions.default_TriggerClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean GripClick
        {
            get
            {
                return SteamVR_Actions.default_GripClick;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
